//
//  WFChatClient.h
//  WFChatClient
//
//  Created by heavyrain on 2017/11/5.
//  Copyright © 2024 WildFireChat. All rights reserved.
//

#import <UIKit/UIKit.h>

//! Project version number for WFChatClient.
FOUNDATION_EXPORT double XQQChatClientVersionNumber;

//! Project version string for WFChatClient.
FOUNDATION_EXPORT const unsigned char XQQChatClientVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import "PublicHeader.h"


#import "XQQIMService.h"
#import "XQQNetworkService.h"
#import "Common.h"
#import "XQQCProtocol.h"
#import "XQQCJsonSerializer.h"
#import "XQQCMessage.h"
#import "XQQCMessageContent.h"
#import "XQQCAddGroupeMemberNotificationContent.h"
#import "XQQCCreateGroupNotificationContent.h"
#import "XQQCDismissGroupNotificationContent.h"
#import "XQQCImageMessageContent.h"
#import "XQQCKickoffGroupMemberNotificationContent.h"
#import "XQQCMediaMessageContent.h"
#import "XQQCNotificationMessageContent.h"
#import "XQQCTipNotificationMessageContent.h"
#import "XQQCQuitGroupNotificationContent.h"
#import "XQQCSoundMessageContent.h"
#import "XQQCPTTSoundMessageContent.h"
#import "XQQCFileMessageContent.h"
#import "XQQCTextMessageContent.h"
#import "XQQCPTextMessageContent.h"
#import "XQQCUnknownMessageContent.h"
#import "XQQCChangeGroupNameNotificationContent.h"
#import "XQQCChangeGroupPortraitNotificationContent.h"
#import "XQQCModifyGroupAliasNotificationContent.h"
#import "XQQCTransferGroupOwnerNotificationContent.h"
#import "XQQCStickerMessageContent.h"
#import "XQQCLocationMessageContent.h"
#import "XQQCCallStartMessageContent.h"
//#import "WFCCCallAddParticipantMessageContent.h"
//#import "WFCCCallByeMessageContent.h"
#import "XQQCTypingMessageContent.h"
#import "XQQCRecallMessageContent.h"
#import "XQQCVideoMessageContent.h"
#import "XQQCFriendAddedMessageContent.h"
#import "XQQCFriendGreetingMessageContent.h"
#import "XQQCGroupPrivateChatNotificationContent.h"
#import "XQQCGroupJoinTypeNotificationContent.h"
#import "XQQCGroupSetManagerNotificationContent.h"
#import "XQQCGroupMemberMuteNotificationContent.h"
#import "XQQCGroupMemberAllowNotificationContent.h"
//#import "WFCCDeleteMessageContent.h"
#import "XQQCGroupMuteNotificationContent.h"
#import "XQQCPCLoginRequestMessageContent.h"
#import "XQQCCardMessageContent.h"
//#import "WFCCThingsDataContent.h"
//#import "WFCCThingsLostEventContent.h"
#import "XQQCConferenceInviteMessageContent.h"
#import "XQQCCompositeMessageContent.h"
#import "XQQCLinkMessageContent.h"
#import "XQQCChannelMenu.h"
#import "XQQCKickoffGroupMemberVisibleNotificationContent.h"
#import "XQQCQuitGroupVisibleNotificationContent.h"
#import "XQQCModifyGroupMemberExtraNotificationContent.h"
#import "XQQCModifyGroupExtraNotificationContent.h"
#import "XQQCChannelMenuEventMessageContent.h"
#import "XQQCStartSecretChatMessageContent.h"
#import "XQQCEnterChannelChatMessageContent.h"
#import "XQQCLeaveChannelChatMessageContent.h"
//#import "XQQCJoinCallRequestMessageContent.h"
#import "XQQCGroupSettingsNotificationContent.h"
//#import "WFCCMultiCallOngoingMessageContent.h"
#import "XQQCRichNotificationMessageContent.h"
#import "XQQCArticlesMessageContent.h"
#import "XQQCRawMessageContent.h"
#import "XQQCConversation.h"
#import "XQQCConversationInfo.h"
#import "XQQCConversationSearchInfo.h"
#import "XQQCGroupSearchInfo.h"
#import "XQQCFriendRequest.h"
#import "XQQCFriend.h"
#import "XQQCGroupInfo.h"
#import "XQQCGroupMember.h"
#import "XQQCUserInfo.h"
#import "XQQCChatroomInfo.h"
#import "XQQCUnreadCount.h"
#import "XQQCUtilities.h"
#import "XQQCPCOnlineInfo.h"
#import "XQQCDeliveryReport.h"
#import "XQQCReadReport.h"
#import "XQQCFileRecord.h"
#import "XQQCQuoteInfo.h"
#import "XQQCUserOnlineState.h"
#import "XQQCSecretChatInfo.h"
#import "XQQCEnums.h"
#import "XQQCAnnouncementMessageContent.h"

#import "MJExtension.h"
#import "XQQUserExtraInfo.h"
#import "JSONHelper.h"
#import "XQQUserDB.h"
#import "XQQCUserTag.h"
#import "XQQCSign.h"
#import "XQQCResign.h"
#import "XQQCSignTasks.h"
#import "XQQCSignHistory.h"
#import "XQQCPointsHistory.h"



